package cli

import (
	"context"
	"flag"
	"io"
	"os"

	"golang.org/x/term"
)

// ActionFunc is the command execution function: context, input (args+flags), output (logging/table/ask).
type ActionFunc func(context.Context, *Input, *Output) error

// BeforeFunc is a hook function run before Action. It may derive a new context and
// return it; the updated context is passed to Action/After and subsequent hooks.
type BeforeFunc func(context.Context, *Input, *Output) (context.Context, error)

// HookFunc is the After hook function with the same signature as Action.
type HookFunc func(context.Context, *Input, *Output) error

// CommandNotFoundFunc handles a command that was not found.
type CommandNotFoundFunc func(context.Context, *Input, *Output, string)

// VersionPrinterFunc customizes version printing. When unset, the default implementation is used.
type VersionPrinterFunc func(context.Context, *Input, *Output)

// Command is the command struct. The root command is the App; both are the same type.
type Command struct {
	// Metadata
	Name        string   // Command name; usually empty for the root command (App)
	Aliases     []string // Command aliases; the command can be invoked by any alias
	Usage       string   // One-line purpose description, shown in the help listing
	UsageText   string   // Custom usage line; generated by the library by default
	Description string   // Detailed command description, shown in help
	ArgsUsage   string   // Usage description for positional arguments (e.g. "<name> [flags]")
	Hidden      bool     // When true, hidden from help/listing but still directly invocable
	Version     string   // Version of the root command (App); enables --version/-v

	// Behavior
	Flags           []Flag              // Flags defined by this command
	Subcommands     []*Command          // List of subcommands
	Before          BeforeFunc          // Hook run before execution; may return an updated context
	After           HookFunc            // Hook run after execution (invoked after a subcommand runs)
	Action          ActionFunc          // Command execution function
	CommandNotFound CommandNotFoundFunc // Handler for when a command is not found
	VersionPrinter  VersionPrinterFunc  // Custom version printing function

	// Runtime state (unexported)
	app          *Command               // Root command
	parent       *Command               // Parent command
	values       map[string]interface{} // Flag name -> underlying value (*singleValue / *sliceValue / *boolValue)
	setFlags     map[string]bool        // Set of flag names explicitly set
	builtinFlags []Flag                 // Automatically registered global builtin flags (--verbose/--quiet/--no-interaction)
	out          *Output                // Shared output object
	interactive  bool                   // Whether interactive Q&A is allowed
	Stdin        io.Reader              // Injectable standard input (defaults to os.Stdin)
	helpValue    *boolValue             // Underlying value for the builtin --help/-h
	versionValue *boolValue             // Underlying value for the builtin --version/-v
}

// App is a type alias for the root command. Usage: `app := &cli.App{...}`.
type App = Command

// New creates an empty root command.
func New() *Command { return &Command{} }

// Run executes the command. args should include the program name (pass os.Args directly):
// `app.Run(ctx, os.Args)`.
func (c *Command) Run(ctx context.Context, args []string) error {
	if len(args) > 0 {
		args = args[1:] // drop the program name
	}
	return c.run(ctx, args)
}

// run executes the command; args excludes the program name.
func (c *Command) run(ctx context.Context, args []string) error {
	if c.app == nil {
		c.app = c
		// Non-terminal input defaults to non-interactive; an explicitly injected
		// Stdin is treated as intentional interaction (for testing and embedding).
		c.interactive = term.IsTerminal(int(os.Stdin.Fd()))
		if c.Stdin != nil {
			c.interactive = true
		}
		c.setupGlobalFlags()
	}

	rest, err := c.parse(args)
	if err != nil {
		return err
	}

	// Set the shared output level based on the global verbose/quiet flags (after root parse).
	if c.app == c {
		out := c.output()
		if bv, ok := c.app.values["verbose"].(*boolValue); ok && bv.val {
			out.SetVerbosity(VerbosityDebug)
		}
		if bv, ok := c.app.values["quiet"].(*boolValue); ok && bv.val {
			out.SetVerbosity(VerbosityQuiet)
		}
	}

	if c.helpValue != nil && c.helpValue.val {
		return c.showHelp(ctx)
	}
	if c.versionValue != nil && c.versionValue.val {
		c.printVersion(ctx, c.newInput(rest))
		return nil
	}

	// Global (root) Before hook; runs only once for the whole invocation.
	// The context it returns is used for the rest of the run.
	if c.app == c && c.Before != nil {
		var err error
		if ctx, err = c.Before(ctx, c.newInput(rest), c.output()); err != nil {
			return err
		}
	}

	// Subcommand dispatch (rest[0] is treated as a command name only when subcommands are declared).
	if len(rest) > 0 && len(c.Subcommands) > 0 {
		if sub := c.findSubcommand(rest[0]); sub != nil {
			sub.app = c.app
			sub.parent = c
			return c.finish(ctx, rest, sub.run(ctx, rest[1:]))
		}
		if c.app == c { // Known builtin commands not matched on the root command
			switch rest[0] {
			case "help":
				return c.finish(ctx, rest, c.runHelp(ctx, rest[1:]))
			case "version":
				if c.Version != "" {
					c.printVersion(ctx, c.newInput(rest[1:]))
					return c.finish(ctx, rest, nil)
				}
			}
			if c.CommandNotFound != nil {
				c.CommandNotFound(ctx, c.newInput(rest[1:]), c.output(), rest[0])
				return c.finish(ctx, rest, nil)
			}
			return c.finish(ctx, rest, &NotFoundError{Command: rest[0]})
		}
	}

	// No subcommand: execute the current command.
	if c.Action != nil {
		return c.finish(ctx, rest, c.execute(ctx, c.newInput(rest), c.output()))
	}
	// A command without an Action (e.g. a root App used only as a command group) shows help by default.
	return c.finish(ctx, rest, c.showHelp(ctx))
}

// finish runs the global (root) After hook after execution.
func (c *Command) finish(ctx context.Context, rest []string, err error) error {
	if c.app == c && c.After != nil {
		if aerr := c.After(ctx, c.newInput(rest), c.output()); aerr != nil {
			return aerr
		}
	}
	return err
}

// execute runs Before / Action / After in order. The context returned by Before is
// passed to Action and After.
func (c *Command) execute(ctx context.Context, in *Input, out *Output) error {
	if c.Before != nil {
		var err error
		if ctx, err = c.Before(ctx, in, out); err != nil {
			return err
		}
	}
	if c.Action != nil {
		if err := c.Action(ctx, in, out); err != nil {
			return err
		}
	}
	if c.After != nil {
		if err := c.After(ctx, in, out); err != nil {
			return err
		}
	}
	return nil
}

// output returns the command's shared output object (created by root on first use;
// subcommands reuse the same instance).
func (c *Command) output() *Output {
	if c.app != nil && c.app.out != nil {
		return c.app.out
	}
	if c.out == nil {
		c.out = NewOutput()
		c.out.root = c
	}
	return c.out
}

// findSubcommand finds a subcommand by name or alias.
func (c *Command) findSubcommand(name string) *Command {
	for _, sub := range c.Subcommands {
		if sub.Name == name {
			return sub
		}
		for _, a := range sub.Aliases {
			if a == name {
				return sub
			}
		}
	}
	return nil
}

// findSubcommandDeep recursively finds a subcommand by name or alias (supports nested command trees).
func (c *Command) findSubcommandDeep(name string) *Command {
	for _, sub := range c.Subcommands {
		if sub.Name == name {
			return sub
		}
		for _, a := range sub.Aliases {
			if a == name {
				return sub
			}
		}
		if found := sub.findSubcommandDeep(name); found != nil {
			return found
		}
	}
	return nil
}

// hasFlag reports whether the command already defines a flag (including global builtins).
func (c *Command) hasFlag(name string) bool {
	for _, f := range c.Flags {
		for _, n := range f.Names() {
			if n == name {
				return true
			}
		}
	}
	return false
}

// setupGlobalFlags registers out-of-the-box global flags on the root command: --verbose,
// --quiet, --no-interaction. Auto-registration is skipped when the user defines a flag
// with the same name.
func (c *Command) setupGlobalFlags() {
	if !c.hasFlag("verbose") {
		c.builtinFlags = append(c.builtinFlags, &BoolFlag{Name: "verbose", Usage: "enable verbose output"})
	}
	if !c.hasFlag("quiet") {
		c.builtinFlags = append(c.builtinFlags, &BoolFlag{Name: "quiet", Usage: "suppress all output"})
	}
	if !c.hasFlag("no-interaction") {
		c.builtinFlags = append(c.builtinFlags, &BoolFlag{Name: "no-interaction", Usage: "do not ask any interactive question"})
	}
}

// allFlags returns the merged list of the command's own flags and the global builtin flags.
func (c *Command) allFlags() []Flag {
	if c.app != c {
		return c.Flags
	}
	out := make([]Flag, 0, len(c.Flags)+len(c.builtinFlags))
	out = append(out, c.Flags...)
	out = append(out, c.builtinFlags...)
	return out
}

// programName returns the basename of the running program.
func programName() string {
	if p := os.Args[0]; p != "" {
		for i := len(p) - 1; i >= 0; i-- {
			if p[i] == '/' {
				return p[i+1:]
			}
		}
		return p
	}
	return "cli"
}

// parse parses the arguments and returns the remaining positional arguments.
func (c *Command) parse(args []string) ([]string, error) {
	c.values = map[string]interface{}{}
	c.setFlags = map[string]bool{}
	defs := map[string]*flagDef{}

	register := func(names []string, val flag.Value) {
		for _, n := range names {
			defs[n] = &flagDef{value: val, isBool: isBoolFlag(val)}
			c.values[n] = val
		}
	}

	// Builtin --help / -h
	hv := &boolValue{}
	register([]string{"help", "h"}, hv)
	c.helpValue = hv

	// Builtin --version / -v (root command only, when Version is set)
	if c.app == c && c.Version != "" {
		vv := &boolValue{}
		register([]string{"version", "v"}, vv)
		c.versionValue = vv
	}

	// User flags + global builtin flags
	for _, f := range c.allFlags() {
		if err := f.register(register); err != nil {
			return nil, err
		}
	}

	rest, err := parseTokens(args, defs, c.setFlags, len(c.Subcommands) == 0)
	if err != nil {
		return nil, err
	}

	// Value source fallback: when a flag is not explicitly set, try its declared ValueSource in order.
	for _, f := range c.allFlags() {
		if c.flagSetAny(f.Names()) {
			continue
		}
		src := f.source()
		if src == nil {
			continue
		}
		if v, ok := src.Lookup(); ok {
			if def, ok := defs[f.Names()[0]]; ok {
				_ = def.value.Set(v)
				c.setFlags[f.Names()[0]] = true
			}
		}
	}

	// Required flag validation (skipped for --help/--version so help is not blocked by required flags).
	skipRequired := (c.helpValue != nil && c.helpValue.val) ||
		(c.versionValue != nil && c.versionValue.val)
	if !skipRequired {
		for _, f := range c.allFlags() {
			if f.IsRequired() && !c.flagSetAny(f.Names()) {
				return nil, &UsageError{Msg: "Required flag \"" + f.Names()[0] + "\" not set"}
			}
		}
	}

	return rest, nil
}

// flagSetAny reports whether any flag in names was explicitly set.
func (c *Command) flagSetAny(names []string) bool {
	for _, n := range names {
		if c.setFlags[n] {
			return true
		}
	}
	return false
}

// runHelp handles the builtin `help [command]` subcommand.
func (c *Command) runHelp(ctx context.Context, args []string) error {
	if len(args) == 0 {
		return c.showHelp(ctx)
	}
	sub := c.findSubcommand(args[0])
	if sub == nil {
		return &NotFoundError{Command: args[0]}
	}
	sub.app = c.app
	sub.parent = c
	return sub.showHelp(ctx)
}

// printVersion prints version info, preferring a custom VersionPrinter,
// otherwise printing the Version or the program name.
func (c *Command) printVersion(ctx context.Context, in *Input) {
	if c.VersionPrinter != nil {
		c.VersionPrinter(ctx, in, c.output())
		return
	}
	if c.Version != "" {
		c.output().Info(c.Version)
	} else {
		c.output().Info(programName())
	}
}
